# Generated by Django 3.1 on 2020-10-08 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("profiles", "0004_auto_20200723_1448")]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="image/%Y/%m/%d/",
                verbose_name="Avatar",
            ),
        )
    ]
