# @format

version: "3"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    image: mystories
    build: .
    command: bash -c "python /code/manage.py migrate --noinput && gunicorn mystories.wsgi:application --bind 0.0.0.0:8000 --reload"
    volumes:
      - .:/code
      - ./media:/code/media
    links:
      - db
      - redis

  redis:
    image: redis:alpine


  worker:
    image: mystories
    restart: "no"
    command: celery -A mystories worker
    volumes:
      - .:/code
    links:
      - redis

  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./media:/media
      - ./static_files:/static
    links:
      - web
