# Generated by Django 3.0.7 on 2020-06-04 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [("stories", "0001_initial"), ("profiles", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="story",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stories",
                to="profiles.Profile",
            ),
        ),
        migrations.AddField(
            model_name="story",
            name="tags",
            field=models.ManyToManyField(related_name="stories", to="stories.Tag"),
        ),
        migrations.AddField(
            model_name="comment",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="profiles.Profile",
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="story",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="stories.History",
            ),
        ),
    ]
