# Generated by Django 3.0.8 on 2020-07-23 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("stories", "0006_auto_20200615_1920")]

    operations = [
        migrations.AddField(
            model_name="story",
            name="body_markdown",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="story",
            name="image",
            field=models.ImageField(
                blank=True,
                default="history_default.png",
                null=True,
                upload_to="image/%Y/%m/%d/",
                verbose_name="Avatar",
            ),
        ),
        migrations.AddField(
            model_name="story",
            name="language",
            field=models.CharField(
                choices=[("en", "English"), ("es", "Spanish"), ("de", "German")],
                default="en",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="story",
            name="body",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="story",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
