# Generated by Django 3.0.7 on 2020-06-04 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("histories", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("bio", models.TextField(blank=True)),
                ("image", models.URLField(blank=True)),
                (
                    "favorites",
                    models.ManyToManyField(
                        related_name="favorited_by", to="histories.History"
                    ),
                ),
                (
                    "follows",
                    models.ManyToManyField(
                        related_name="followed_by", to="profiles.Profile"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ["-created_at", "-updated_at"], "abstract": False},
        )
    ]
