# Generated by Django 3.0.8 on 2020-07-23 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("profiles", "0003_auto_20200723_1258")]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                blank=True,
                default="avatar_default.png",
                null=True,
                upload_to="image/%Y/%m/%d/",
                verbose_name="Avatar",
            ),
        )
    ]
