# Generated by Django 3.0.7 on 2020-06-15 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("stories", "0005_auto_20200615_1909")]

    operations = [
        migrations.RenameField(
            model_name="speech", old_name="state", new_name="is_ready"
        )
    ]
