# Generated by Django 3.1 on 2020-10-09 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0005_auto_20201008_1159"),
        ("notifications", "0004_auto_20201008_1132"),
    ]

    operations = [
        migrations.RenameField(
            model_name="notification", old_name="receiver", new_name="owner"
        ),
        migrations.RemoveField(model_name="notification", name="author"),
        migrations.AddField(
            model_name="notification",
            name="sender",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notification",
                to="profiles.profile",
            ),
        ),
    ]
