# Generated by Django 3.1 on 2020-10-27 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("notifications", "0005_auto_20201009_1407")]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="optional",
            field=models.CharField(blank=True, max_length=255, null=True),
        )
    ]
