# @format

version: "3"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    image: myhistories
    build: .
    command: bash -c "python /code/manage.py migrate --noinput && python /code/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
      - ./media:/code/media
    ports:
      - "8000:8000"
    links:
      - db
      - broker

  broker:
    image: rabbitmq:latest
    hostname: broker
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=mypass
    ports:
      - "5672:5672"

  worker:
    image: myhistories
    restart: "no"
    command: celery -A myhistories worker
    volumes:
      - .:/code
    links:
      - broker

  flower:
    image: mher/flower
    command: ["flower", "--broker=amqp://admin:mypass@broker", "--port=5555"]
    ports:
      - 5555:5555
    links:
      - broker
