# @format

version: "3"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    image: mystories
    build: .
    command: bash -c "python /code/manage.py migrate --noinput && gunicorn mystories.wsgi:application --bind 0.0.0.0:8000 --reload"
    volumes:
      - .:/code
      - ./media:/code/media
    links:
      - db
      - broker

  broker:
    image: rabbitmq:latest
    hostname: broker
    environment:
      - RABBITMQ_DEFAULT_USER=adminrabbit
      - RABBITMQ_DEFAULT_PASS=mypass123
    ports:
      - "5672:5672"

  worker:
    image: mystories
    restart: "no"
    command: celery -A mystories worker
    volumes:
      - .:/code
    links:
      - broker

  nginx:
    build: ./nginx
    ports:
      - 8000:8000
    volumes:
      - ./media:/media
      - ./static_files:/static
      - ./dist:/dist
    links:
      - web
