# @format

version: "3"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    image: mystories
    build: .
    command: bash -c "python /code/manage.py migrate --noinput && python /code/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
      - ./media:/code/media
    ports:
      - "8000:8000"
    links:
      - db
      - broker
      - redis

  redis:
        image: redis:3.2.8
        hostname: redis

  broker:
    image: rabbitmq:latest
    hostname: broker
    environment:
      - RABBITMQ_DEFAULT_USER=adminrabbit
      - RABBITMQ_DEFAULT_PASS=mypass123
    ports:
      - "5672:5672"

  worker:
    image: mystories
    restart: "no"
    command: celery -A mystories worker
    volumes:
      - .:/code
    links:
      - broker
      - redis
