# Generated by Django 3.0.8 on 2020-07-29 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("stories", "0007_auto_20200723_1448")]

    operations = [
        migrations.AlterField(
            model_name="speech",
            name="is_ready",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name="speech",
            name="language",
            field=models.CharField(default="en", max_length=10, null=True),
        ),
    ]
