# Generated by Django 3.0.7 on 2020-06-23 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("notifications", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="status",
            field=models.CharField(
                choices=[
                    ("opened", "Opened by someone"),
                    ("send", "It was send"),
                    ("received", "Received by someone"),
                    ("viewed", "Viewed by someone"),
                    ("closed", "Closed - not available anymore"),
                ],
                default=("opened", "Opened by someone"),
                max_length=32,
            ),
        )
    ]
