# Generated by Django 3.0.7 on 2020-06-23 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_auto_20200608_1825"),
        ("notifications", "0002_notification_status"),
    ]

    operations = [
        migrations.RemoveField(model_name="notification", name="receivers"),
        migrations.AddField(
            model_name="notification",
            name="receiver",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mynotification",
                to="profiles.Profile",
            ),
        ),
    ]
